description: Ensure nothing obvious is broken, and pre-cache Go modules.
executor: go-machine
steps:
  # Setup Go enabling the proxy for downloading modules.
  - setup-go:
      GOPROXY: https://proxy.golang.org,direct
  - checkout
  - run:
      name: Check CircleCI CLI version
      command:
        # Print some debug info.
        set -x
        which circleci
        circleci version
  - run: make ci-verify
  - configure-git
  - refresh_go_mod_cache
