name: Ember Asset Sizes

on:
  pull_request:
    # types: [opened, synchronize, labeled] # necessary to watch for when the label is added
    paths:
      - "ui/**"

jobs:
  build:
    # if: ${{ contains(github.event.pull_request.labels.*.name, 'ember-asset-size') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - uses: backspace/ember-asset-size-action@edit-comment
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          working-directory: "ui"
