name: Ember Asset Sizes

on:
  pull_request:
    types: [opened, synchronize, labeled] # necessary to watch for when the label is added
    paths:
      - "ui/**"

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ember-asset-size') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "^10"
      - uses: simplabs/ember-asset-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          working-directory: "ui"
